In [17]:
import pandas as pd
import numpy as np
import pickle

In [2]:
df = pd.read_csv("Crime_Incidents_20241010.csv")

In [3]:
df.shape
print(df.dtypes)
print(df.isnull().sum())

Case Number                 object
Incident Datetime           object
Incident ID                float64
Incident Type Primary       object
Incident Description        object
Parent Incident Type        object
Hour of Day                  int64
Day of Week                 object
Address                     object
City                        object
State                       object
Location                    object
Latitude                    object
Longitude                   object
Created At                  object
updated_at                 float64
zip_code                    object
neighborhood                object
Council District            object
Council District 2011       object
Census Tract                object
Census Block Group          object
Census Block                object
2010 Census Tract           object
2010 Census Block Group     object
2010 Census Block           object
Police District             object
TRACTCE20                   object
GEOID20_tract               object
GEOID20_blockgroup          object
GEOID20_block               object
dtype: object
Case Number                     0
Incident Datetime               0
Incident ID                314817
Incident Type Primary           0
Incident Description            0
Parent Incident Type            0
Hour of Day                     0
Day of Week                     0
Address                        38
City                            0
State                           0
Location                     6263
Latitude                      984
Longitude                     984
Created At                 244064
updated_at                 314817
zip_code                     2368
neighborhood                 3332
Council District             2419
Council District 2011        2368
Census Tract                 3332
Census Block Group           3332
Census Block                 3332
2010 Census Tract            3332
2010 Census Block Group      3332
2010 Census Block            3332
Police District              3332
TRACTCE20                    3195
GEOID20_tract                3195
GEOID20_blockgroup           3195
GEOID20_block                3195
dtype: int64

In [4]:


# Identify the index of the 'Longitude' column
longitude_index = df.columns.get_loc('Longitude')

# Keep only the columns up to and including 'Longitude'
df = df.iloc[:, :longitude_index + 1]

df.drop(columns=['Incident ID'], inplace=True)
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314817 entries, 0 to 314816
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Case Number            314817 non-null  object
 1   Incident Datetime      314817 non-null  object
 2   Incident Type Primary  314817 non-null  object
 3   Incident Description   314817 non-null  object
 4   Parent Incident Type   314817 non-null  object
 5   Hour of Day            314817 non-null  int64
 6   Day of Week            314817 non-null  object
 7   Address                314779 non-null  object
 8   City                   314817 non-null  object
 9   State                  314817 non-null  object
 10  Location               308554 non-null  object
 11  Latitude               313833 non-null  object
 12  Longitude              313833 non-null  object
dtypes: int64(1), object(12)
memory usage: 31.2+ MB
None
Case Number                 0
Incident Datetime           0
Incident Type Primary       0
Incident Description        0
Parent Incident Type        0
Hour of Day                 0
Day of Week                 0
Address                    38
City                        0
State                       0
Location                 6263
Latitude                  984
Longitude                 984
dtype: int64

In [5]:
df= df.dropna()

In [6]:
print(df.head(15))
print(df.shape)

   Case Number       Incident Datetime Incident Type Primary  \
0   16-1660403  06/14/2016 01:20:00 AM               ASSAULT
1   16-3480266  12/13/2016 05:00:00 AM         LARCENY/THEFT
3   14-3210732  11/17/2014 08:08:00 AM         LARCENY/THEFT
4   15-1100268  04/20/2015 10:22:00 AM         LARCENY/THEFT
5   15-1000814  04/10/2015 03:00:00 AM              BURGLARY
7   15-1300836  05/10/2015 08:00:00 AM               ASSAULT
9   16-2870522  10/12/2016 11:52:00 AM         LARCENY/THEFT
10  16-1330802  05/12/2016 05:30:00 AM               ASSAULT
12  14-2610440  08/31/2014 12:00:00 PM         LARCENY/THEFT
14  16-3470932  12/04/2016 09:59:00 AM         LARCENY/THEFT
15  17-1290784  05/09/2017 09:16:00 AM         LARCENY/THEFT
16  16-0250656  01/25/2016 05:43:00 AM         LARCENY/THEFT
18  16-3210673  11/16/2016 05:46:00 AM         LARCENY/THEFT
20  15-1900228  07/01/2015 12:00:00 PM         LARCENY/THEFT
21  17-1911010  07/10/2017 11:45:00 AM              BURGLARY

   Incident Description Parent Incident Type  Hour of Day Day of Week  \
0               ASSAULT              Assault            1     Tuesday
1         LARCENY/THEFT                Theft            5     Tuesday
3         LARCENY/THEFT                Theft            8      Monday
4         LARCENY/THEFT                Theft           10      Monday
5              BURGLARY  Breaking & Entering            3      Friday
7               ASSAULT              Assault            8      Sunday
9         LARCENY/THEFT                Theft           11   Wednesday
10              ASSAULT              Assault            5    Thursday
12        LARCENY/THEFT                Theft           12      Sunday
14        LARCENY/THEFT                Theft            9      Sunday
15        LARCENY/THEFT                Theft            9     Tuesday
16        LARCENY/THEFT                Theft            5      Monday
18        LARCENY/THEFT                Theft            5   Wednesday
20        LARCENY/THEFT                Theft           12   Wednesday
21             BURGLARY  Breaking & Entering           11      Monday

                        Address     City State                Location  \
0   E AMHERST ST & E AMHERST ST  Buffalo    NY  POINT (-78.889 42.938)
1       1000 Block E LOVEJOY ST  Buffalo    NY  POINT (-78.809 42.889)
3         2100 Block ELMWOOD AV  Buffalo    NY  POINT (-78.879 42.954)
4         2100 Block ELMWOOD AV  Buffalo    NY  POINT (-78.879 42.954)
5         400 Block GLENWOOD AV  Buffalo    NY  POINT (-78.848 42.913)
7              200 Block 7TH ST  Buffalo    NY  POINT (-78.885 42.891)
9             200 Block MAIN ST  Buffalo    NY  POINT (-78.876 42.882)
10          100 Block ASHLEY ST  Buffalo    NY  POINT (-78.825 42.894)
12            1 Block CUSTER ST  Buffalo    NY    POINT (-78.83 42.95)
14      SWEENEY ST & GENESEE ST  Buffalo    NY  POINT (-78.842 42.901)
15     300 Block CONNECTICUT ST  Buffalo    NY  POINT (-78.887 42.906)
16            1 Block GARNER AV  Buffalo    NY  POINT (-78.892 42.925)
18         100 Block BIDWELL PW  Buffalo    NY  POINT (-78.878 42.922)
20          1000 Block GRANT ST  Buffalo    NY    POINT (-78.89 42.94)
21       100 Block E DELAVAN AV  Buffalo    NY   POINT (-78.85 42.922)

   Latitude Longitude
0    42.938   -78.889
1    42.889   -78.809
3    42.954   -78.879
4    42.954   -78.879
5    42.913   -78.848
7    42.891   -78.885
9    42.882   -78.876
10   42.894   -78.825
12    42.95    -78.83
14   42.901   -78.842
15   42.906   -78.887
16   42.925   -78.892
18   42.922   -78.878
20    42.94    -78.89
21   42.922    -78.85
(308517, 13)

In [7]:
df.drop(columns=['Longitude','Incident Datetime', 'Latitude', 'Case Number', 'Location'], inplace=True)

In [8]:
df.head()

,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,State
0,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,NY
1,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,NY
3,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,NY
4,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,NY
5,BURGLARY,BURGLARY,Breaking & Entering,3,Friday,400 Block GLENWOOD AV,Buffalo,NY

In [9]:
df['Address'] = df['Address'].str.extract(r'([A-Z]+\s[A-Z]+)')[0]  # Adjust regex based on your address format

categorical_columns = ['Incident Type Primary','Incident Description', 'Parent Incident Type', 'Day of Week', 'City', 'State', 'Address']
for column in categorical_columns:
    df[column] = df[column].astype('category').cat.codes
df['Hour of Day'] = df['Hour of Day'].apply(lambda x: 1 if x < 8 else 0)

In [10]:
df.head(20)

,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,State
0,2,2,0,1,5,1313,0,0
1,8,7,7,1,5,1331,0,0
3,8,7,7,0,1,1429,0,0
4,8,7,7,0,1,1429,0,0
5,4,3,1,1,0,1665,0,0
7,2,2,0,0,3,3513,0,0
9,8,7,7,0,6,2354,0,0
10,2,2,0,1,4,147,0,0
12,8,7,7,0,3,1160,0,0
14,8,7,7,0,3,3470,0,0
15,8,7,7,0,5,1081,0,0
16,8,7,7,1,1,1596,0,0
18,8,7,7,1,6,259,0,0
20,8,7,7,0,6,1697,0,0
21,4,3,1,0,1,1315,0,0
22,8,7,7,0,0,1562,0,0
24,8,7,7,0,1,1947,0,0
25,2,2,0,0,3,2859,0,0
27,4,3,1,1,1,2888,0,0
29,8,7,7,0,2,2774,0,0

In [11]:

Y =df['Hour of Day'].values
X = df.drop(columns=['Hour of Day'])

# X = (X - X.mean(axis=0)) / X.std(axis=0)

In [12]:
import random
N = X.shape[0]
indices = list(range(N))
random.seed(123)
random.shuffle(indices)

train_size = int(0.8 * N)
train_indices = indices[:train_size]
test_indices = indices[train_size:]

X_train = X.iloc[train_indices]
Y_train = Y[train_indices]
X_test = X.iloc[test_indices]
Y_test = Y[test_indices]

print("Shape of X_train: ",X_train.shape,"Shape of X_test: ",X_test.shape)
print("Shape of Y_train: ",Y_train.shape,"Shape of Y_test: ",Y_test.shape)

Shape of X_train:  (246813, 7) Shape of X_test:  (61704, 7)
Shape of Y_train:  (246813,) Shape of Y_test:  (61704,)

In [13]:

class LogitRegression():
    def __init__(self, learning_rate=0.005, iterations=5000):
        self.learning_rate = learning_rate
        self.iterations = iterations

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def cost(self, h, y):
        m = len(y)
        return (-1 / m) * np.sum(y * np.log(h + 1e-10) + (1 - y) * np.log(1 - h + 1e-10))

    def gradient_descent(self, X, y, h):
        m = len(y)
        delta = h - y.flatten()
        dW = (1 / m) * np.dot(X.T, delta)
        db = (1 / m) * np.sum(delta)
        self.w -= self.learning_rate * dW
        self.b -= self.learning_rate * db

    def fit(self, X, y):
        X = np.array(X, dtype=float)
        y = np.array(y, dtype=float).flatten()

        assert X.ndim == 2
        assert y.ndim == 1
        assert X.shape[0] == y.shape[0]

        self.w = np.random.uniform(0, 1, X.shape[1])
        self.b = 0
        self.losses = []

        for i in range(self.iterations):
            z = np.dot(X, self.w) + self.b
            h = self.sigmoid(z)

            loss = self.cost(h, y)
            self.losses.append(loss)

            self.gradient_descent(X, y, h)

            if i % 100 == 0:
                print(f'Iteration {i}, Loss: {loss}')

    def predict(self, X):
        z = np.dot(X, self.w) + self.b
        h = self.sigmoid(z)
        return np.where(h >= 0.5, 1, 0)

    def save_weights(self, file_name="model_weights.pkl"):
        with open(file_name, 'wb') as file:
            pickle.dump({'weights': self.w, 'bias': self.b}, file)
        print(f"Weights and bias saved to {file_name}")

In [14]:
model = LogitRegression()
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

Iteration 0, Loss: 16.210792591971988

/var/folders/c1/1s6rg9v95b5_yr464y1gxkfh0000gn/T/ipykernel_6531/1231197439.py:7: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))

Iteration 100, Loss: 16.16684950889475
Iteration 200, Loss: 16.12150860076212
Iteration 300, Loss: 16.076764757091492
Iteration 400, Loss: 16.036776751215573
Iteration 500, Loss: 16.00910177705157
Iteration 600, Loss: 15.992489337611437
Iteration 700, Loss: 15.992604962470102
Iteration 800, Loss: 15.99935223475525
Iteration 900, Loss: 16.007898655543883
Iteration 1000, Loss: 16.01582507007952
Iteration 1100, Loss: 16.024317959262444
Iteration 1200, Loss: 16.031577732158663
Iteration 1300, Loss: 6.2497691568140485
Iteration 1400, Loss: 6.2402711554698
Iteration 1500, Loss: 6.232391701978999
Iteration 1600, Loss: 6.226298297223524
Iteration 1700, Loss: 6.22128928429071
Iteration 1800, Loss: 6.217488999854022
Iteration 1900, Loss: 6.214321273581672
Iteration 2000, Loss: 6.211951841561531
Iteration 2100, Loss: 6.209929708377965
Iteration 2200, Loss: 6.208412763514422
Iteration 2300, Loss: 6.207055811671927
Iteration 2400, Loss: 6.206075450030984
Iteration 2500, Loss: 6.205151776269731
Iteration 2600, Loss: 6.204547471407516
Iteration 2700, Loss: 6.226549381225496
Iteration 2800, Loss: 6.224545249747103
Iteration 2900, Loss: 6.222265692282956
Iteration 3000, Loss: 6.199574600729
Iteration 3100, Loss: 6.199277672949839
Iteration 3200, Loss: 6.199190018980689
Iteration 3300, Loss: 16.00364216513945
Iteration 3400, Loss: 16.010160386278084
Iteration 3500, Loss: 6.19158532418503
Iteration 3600, Loss: 15.426640389461049
Iteration 3700, Loss: 15.834763953689242
Iteration 3800, Loss: 15.951432935587508
Iteration 3900, Loss: 15.968081786942559
Iteration 4000, Loss: 6.231102425880408
Iteration 4100, Loss: 6.229332192455435
Iteration 4200, Loss: 6.220982195243678
Iteration 4300, Loss: 6.2196904918788904
Iteration 4400, Loss: 6.2079963974620105
Iteration 4500, Loss: 6.207791759723232
Iteration 4600, Loss: 6.207367636629227
Iteration 4700, Loss: 6.207201941902725
Iteration 4800, Loss: 6.204192837349804
Iteration 4900, Loss: 6.204085566906709

In [19]:
# print(y_pred[:10])
# print(Y_test[:10])
correct_predictions = np.sum(y_pred == Y_test)

accuracy = correct_predictions / len(Y_test) * 100
print(accuracy)
model.save_weights('Pavithran_Assignment1_bonus.pkl')

72.19629197458836
Weights and bias saved to Pavithran_Assignment1_bonus.pkl